# Generated by Django 4.0.1 on 2022-04-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcanary', '0002_advert_honey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_mark',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='car',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarMark',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
