# Generated by Django 4.0.1 on 2022-04-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcanary', '0003_remove_carmodel_car_mark_remove_advert_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=300)),
                ('canary', models.CharField(max_length=500)),
            ],
        ),
    ]
