# Generated by Django 4.0.1 on 2022-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcanary', '0004_canary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canary',
            name='table',
            field=models.TextField(max_length=300),
        ),
    ]
